version: "3"

services:
  gazuz_bot:
    image: gazuz_bot
    container_name: gazuz_bot
    build: ./
    restart: always
    volumes:
      - ./:/app
networks:
  default:
    external:
      name: nginx-proxy