# Generated by Django 3.1.6 on 2021-02-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('province_id', models.CharField(max_length=30)),
                ('district_id', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
            ],
        ),
    ]
