# Generated by Django 3.1.6 on 2021-05-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.user')),
            ],
            options={
                'managed': False,
            },
            bases=('bot.user',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.user')),
            ],
            options={
                'managed': False,
            },
            bases=('bot.user',),
        ),
    ]
